/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EntireCollectionRouteImport } from './routes/entire-collection'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as InventoryAddRouteImport } from './routes/inventory/add'
import { Route as InventoryEditionIdRouteImport } from './routes/inventory/$editionId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections/$collectionId/index'
import { Route as CollectionsCollectionIdGameEditionEditionIdRouteImport } from './routes/collections/$collectionId/gameEdition/$editionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EntireCollectionRoute = EntireCollectionRouteImport.update({
  id: '/entire-collection',
  path: '/entire-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAddRoute = InventoryAddRouteImport.update({
  id: '/inventory/add',
  path: '/inventory/add',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryEditionIdRoute = InventoryEditionIdRouteImport.update({
  id: '/inventory/$editionId',
  path: '/inventory/$editionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CollectionsCollectionIdRoute,
  } as any)
const CollectionsCollectionIdGameEditionEditionIdRoute =
  CollectionsCollectionIdGameEditionEditionIdRouteImport.update({
    id: '/gameEdition/$editionId',
    path: '/gameEdition/$editionId',
    getParentRoute: () => CollectionsCollectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entire-collection': typeof EntireCollectionRoute
  '/settings': typeof SettingsRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRouteWithChildren
  '/inventory/$editionId': typeof InventoryEditionIdRoute
  '/inventory/add': typeof InventoryAddRoute
  '/collections/': typeof CollectionsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/gameEdition/$editionId': typeof CollectionsCollectionIdGameEditionEditionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entire-collection': typeof EntireCollectionRoute
  '/settings': typeof SettingsRoute
  '/inventory/$editionId': typeof InventoryEditionIdRoute
  '/inventory/add': typeof InventoryAddRoute
  '/collections': typeof CollectionsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/gameEdition/$editionId': typeof CollectionsCollectionIdGameEditionEditionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/entire-collection': typeof EntireCollectionRoute
  '/settings': typeof SettingsRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRouteWithChildren
  '/inventory/$editionId': typeof InventoryEditionIdRoute
  '/inventory/add': typeof InventoryAddRoute
  '/collections/': typeof CollectionsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/gameEdition/$editionId': typeof CollectionsCollectionIdGameEditionEditionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/entire-collection'
    | '/settings'
    | '/collections/$collectionId'
    | '/inventory/$editionId'
    | '/inventory/add'
    | '/collections/'
    | '/inventory/'
    | '/collections/$collectionId/'
    | '/collections/$collectionId/gameEdition/$editionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/entire-collection'
    | '/settings'
    | '/inventory/$editionId'
    | '/inventory/add'
    | '/collections'
    | '/inventory'
    | '/collections/$collectionId'
    | '/collections/$collectionId/gameEdition/$editionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/entire-collection'
    | '/settings'
    | '/collections/$collectionId'
    | '/inventory/$editionId'
    | '/inventory/add'
    | '/collections/'
    | '/inventory/'
    | '/collections/$collectionId/'
    | '/collections/$collectionId/gameEdition/$editionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EntireCollectionRoute: typeof EntireCollectionRoute
  SettingsRoute: typeof SettingsRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRouteWithChildren
  InventoryEditionIdRoute: typeof InventoryEditionIdRoute
  InventoryAddRoute: typeof InventoryAddRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entire-collection': {
      id: '/entire-collection'
      path: '/entire-collection'
      fullPath: '/entire-collection'
      preLoaderRoute: typeof EntireCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/add': {
      id: '/inventory/add'
      path: '/inventory/add'
      fullPath: '/inventory/add'
      preLoaderRoute: typeof InventoryAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$editionId': {
      id: '/inventory/$editionId'
      path: '/inventory/$editionId'
      fullPath: '/inventory/$editionId'
      preLoaderRoute: typeof InventoryEditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/': {
      id: '/collections/$collectionId/'
      path: '/'
      fullPath: '/collections/$collectionId/'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof CollectionsCollectionIdRoute
    }
    '/collections/$collectionId/gameEdition/$editionId': {
      id: '/collections/$collectionId/gameEdition/$editionId'
      path: '/gameEdition/$editionId'
      fullPath: '/collections/$collectionId/gameEdition/$editionId'
      preLoaderRoute: typeof CollectionsCollectionIdGameEditionEditionIdRouteImport
      parentRoute: typeof CollectionsCollectionIdRoute
    }
  }
}

interface CollectionsCollectionIdRouteChildren {
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
  CollectionsCollectionIdGameEditionEditionIdRoute: typeof CollectionsCollectionIdGameEditionEditionIdRoute
}

const CollectionsCollectionIdRouteChildren: CollectionsCollectionIdRouteChildren =
  {
    CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
    CollectionsCollectionIdGameEditionEditionIdRoute:
      CollectionsCollectionIdGameEditionEditionIdRoute,
  }

const CollectionsCollectionIdRouteWithChildren =
  CollectionsCollectionIdRoute._addFileChildren(
    CollectionsCollectionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EntireCollectionRoute: EntireCollectionRoute,
  SettingsRoute: SettingsRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRouteWithChildren,
  InventoryEditionIdRoute: InventoryEditionIdRoute,
  InventoryAddRoute: InventoryAddRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
