/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as InventoryAddRouteImport } from './routes/inventory/add'
import { Route as InventoryEditionIdRouteImport } from './routes/inventory/$editionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAddRoute = InventoryAddRouteImport.update({
  id: '/inventory/add',
  path: '/inventory/add',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryEditionIdRoute = InventoryEditionIdRouteImport.update({
  id: '/inventory/$editionId',
  path: '/inventory/$editionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/inventory/$editionId': typeof InventoryEditionIdRoute
  '/inventory/add': typeof InventoryAddRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/inventory/$editionId': typeof InventoryEditionIdRoute
  '/inventory/add': typeof InventoryAddRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/inventory/$editionId': typeof InventoryEditionIdRoute
  '/inventory/add': typeof InventoryAddRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/settings'
    | '/inventory/$editionId'
    | '/inventory/add'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/settings'
    | '/inventory/$editionId'
    | '/inventory/add'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/settings'
    | '/inventory/$editionId'
    | '/inventory/add'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  InventoryEditionIdRoute: typeof InventoryEditionIdRoute
  InventoryAddRoute: typeof InventoryAddRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/add': {
      id: '/inventory/add'
      path: '/inventory/add'
      fullPath: '/inventory/add'
      preLoaderRoute: typeof InventoryAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$editionId': {
      id: '/inventory/$editionId'
      path: '/inventory/$editionId'
      fullPath: '/inventory/$editionId'
      preLoaderRoute: typeof InventoryEditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  InventoryEditionIdRoute: InventoryEditionIdRoute,
  InventoryAddRoute: InventoryAddRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
